spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mtec
    password: 9LxQmTg8YPu84SSQ_
    url: jdbc:mysql://localhost:3306/vanderbar
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      format-sql: true
      use_sql_comments: false

